// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Курсовой_Конфигуратор_ПК.Data;

#nullable disable

namespace PCConfigurator.UI.Migrations
{
    [DbContext(typeof(PCConfiguratorContext))]
    partial class PCConfiguratorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Configuration", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigurationId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Gpuid")
                        .HasColumnType("int")
                        .HasColumnName("GPUId");

                    b.Property<int>("MotherboardId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProcessorId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ConfigurationId");

                    b.HasIndex("Gpuid");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("ProcessorId");

                    b.HasIndex("UserId");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.ConfigurationRam", b =>
                {
                    b.Property<int>("ConfigurationRamid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConfigurationRAMId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigurationRamid"));

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Ramid")
                        .HasColumnType("int")
                        .HasColumnName("RAMId");

                    b.HasKey("ConfigurationRamid");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("Ramid");

                    b.ToTable("ConfigurationRAM", (string)null);
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.ConfigurationStorage", b =>
                {
                    b.Property<int>("ConfigurationStorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigurationStorageId"));

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.HasKey("ConfigurationStorageId");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("StorageId");

                    b.ToTable("ConfigurationStorage", (string)null);
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Gpu", b =>
                {
                    b.Property<int>("Gpuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GPUId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gpuid"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("Memory")
                        .HasColumnType("int");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PowerConsumption")
                        .HasColumnType("int");

                    b.HasKey("Gpuid");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("GPUs", (string)null);
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufacturerId"));

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ManufacturerId");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Motherboard", b =>
                {
                    b.Property<int>("MotherboardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotherboardId"));

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("MaxRam")
                        .HasColumnType("int")
                        .HasColumnName("MaxRAM");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ramtype")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RAMType");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MotherboardId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Processor", b =>
                {
                    b.Property<int>("ProcessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessorId"));

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<decimal>("Frequency")
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProcessorId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Processors");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Ram", b =>
                {
                    b.Property<int>("Ramid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RAMId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ramid"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Ramid");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("RAM", (string)null);
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Storage", b =>
                {
                    b.Property<int>("StorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StorageId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Interface")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StorageId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Storage", (string)null);
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("user");

                    b.HasKey("UserId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Configuration", b =>
                {
                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Gpu", "Gpu")
                        .WithMany("Configurations")
                        .HasForeignKey("Gpuid")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Motherboard", "Motherboard")
                        .WithMany("Configurations")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Processor", "Processor")
                        .WithMany("Configurations")
                        .HasForeignKey("ProcessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.User", "User")
                        .WithMany("Configurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gpu");

                    b.Navigation("Motherboard");

                    b.Navigation("Processor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.ConfigurationRam", b =>
                {
                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Configuration", "Configuration")
                        .WithMany("ConfigurationRams")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Ram", "Ram")
                        .WithMany("ConfigurationRams")
                        .HasForeignKey("Ramid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Ram");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.ConfigurationStorage", b =>
                {
                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Configuration", "Configuration")
                        .WithMany("ConfigurationStorages")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Storage", "Storage")
                        .WithMany("ConfigurationStorages")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Configuration");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Gpu", b =>
                {
                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Manufacturer", "Manufacturer")
                        .WithMany("Gpus")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Motherboard", b =>
                {
                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Manufacturer", "Manufacturer")
                        .WithMany("Motherboards")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Processor", b =>
                {
                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Manufacturer", "Manufacturer")
                        .WithMany("Processors")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Ram", b =>
                {
                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Manufacturer", "Manufacturer")
                        .WithMany("Rams")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Storage", b =>
                {
                    b.HasOne("Курсовой_Конфигуратор_ПК.Models.Manufacturer", "Manufacturer")
                        .WithMany("Storages")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Configuration", b =>
                {
                    b.Navigation("ConfigurationRams");

                    b.Navigation("ConfigurationStorages");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Gpu", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Manufacturer", b =>
                {
                    b.Navigation("Gpus");

                    b.Navigation("Motherboards");

                    b.Navigation("Processors");

                    b.Navigation("Rams");

                    b.Navigation("Storages");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Motherboard", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Processor", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Ram", b =>
                {
                    b.Navigation("ConfigurationRams");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.Storage", b =>
                {
                    b.Navigation("ConfigurationStorages");
                });

            modelBuilder.Entity("Курсовой_Конфигуратор_ПК.Models.User", b =>
                {
                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
